import enum


class KeyWords(enum.Enum):
    armor_class = "Класс Доспеха"
    hitpoints = "Хиты"
    speed = "Скорость"
    saving_throws = "Спасброски"
    damage_immunity = "Иммунитет к урону"
    damage_vulnerability = "Уязвимость к урону"
    damage_resistance = "Сопротивление к урону"
    condition_immunity = "Иммунитет к состоянию"
    senses = "Чувства"
    languages = "Языки"
    challenge_rating = "Опасность"
    proficiency = "Бонус мастерства"
    source = "Источник:"
    habitat = "Местность обитания"

class KeyAbilities(enum.Enum):
    strength = "Сила"
    dexterity = "Ловкость"
    constitution = "Телосложение"
    intelligence = "Интеллект"
    wisdom = "Мудрость"
    charisma = "Харизма"

class KeyAbilitiesShort(enum.Enum):
    strength = "Сил"
    dexterity = "Лов"
    constitution = "Тел"
    intelligence = "Инт"
    wisdom = "Мдр"
    charisma = "Хар"

class SpeedTypes(enum.Enum):
    swimming = "плавая"
    flying = "летая"
    climbing = "лазая"
    digging = "копая"

class DamageSusceptibilityTypes(enum.Enum):
    immunity = "immunity"
    resistance = "resistance"
    normal = "normal"
    vulnerability = "vulnerability"

class DamageTypes(enum.Enum):
    #  "дробящий, колющий, рубящий от немагических атак"
    #  "дробящий, колющий, рубящий от немагических атак, кроме нанесённых посеребрённым оружием"
    #  "дробящий, колющий, рубящий от немагических атак, кроме нанесённых адамантиновым оружием"
    magical = "магических"
    silver = "посеребрённым"
    adamantine = "адамантиновым"
    nonmagical = "немагических"
    slashing = "рубящий"
    piercing = "колющий"
    bludgeoning = "дробящий"
    acid = "кислота"
    cold = "холод"
    fire = "огонь"
    force = "силовое поле"
    lightning = "электричество"
    necrotic = "некротическая энергия"
    poison = "яд"
    psychic = "психическая энергия"
    radiant = "излучение"
    thunder = "звук"

class ConditionImmunityTypes(enum.Enum):
    unconscious = "бессознательность"
    frightened = "испуг"
    invisible = "невидимость"
    incapacitated = "недееспособный"
    deafened = "глухота"
    petrified = "окаменение"
    restrained = "опутанность"
    blinded = "ослепление"
    poisoned = "отравление"
    charmed = "очарование"
    stunned = "ошеломление"
    paralyzed = "паралич"
    prone = "сбивание с ног"
    grappled = "захват"
    exhausted = "истощение"

class SenseTypes(enum.Enum):
    passive_perception = "пассивное Восприятие"
    darkvision = "тёмное зрение"
    blindsight = "слепое зрение"
    truesight = "истинное зрение"
    tremorsense = "чувство вибрации"
    telepathy = "Телепатия"

class SkillTypes(enum.Enum):
    acrobatics = "Акробатика"
    animal_handling = "Уход за животными"
    arcana = "Магия"
    athletics = "Атлетика"
    deception = "Обман"
    history = "История"
    insight = "Проницательность"
    intimidation = "Запугивание"
    investigation = "Расследование"
    medicine = "Медицина"
    nature = "Природа"
    perception = "Восприятие"
    performance = "Выступление"
    persuasion = "Убеждение"
    religion = "Религия"
    sleight_of_hand = "Ловкость рук"
    stealth = "Скрытность"
    survival = "Выживание"

class DescriptionTitles(enum.Enum):
    actions = "Действия"
    legendary_resistance = "Легендарное сопротивление"
    bonus_actions = "Бонусные действия"
    reactions = "Реакции"
    legendary_actions = "Легендарные действия"
    mythic_actions = "Мифические действия"
    lair_actions = "Действия логова"
    lair = "Логово"
    description = "Описание"
    # Местные эффекты относятся к описанию
    areal_effects = "Местные эффекты"